Add support for pushing to remote v2 repos.
Add support to push images to remote v2 repos
Add support to push README.md to remote v2 repos
Add logic in Makefile to handle docker auth

diff --git a/templates/basic/Makefile b/templates/basic/Makefile
--- a/templates/basic/Makefile
+++ b/templates/basic/Makefile
@@ -1,7 +1,9 @@
 #!/usr/bin/make -f
 
 SHELL                   := /usr/bin/env bash
-DOCKER_NAMESPACE        ?= utensils
+REPO_NAMESPACE          ?= utensils
+REPO_USERNAME           ?= jamesbrink
+REPO_API_URL            ?= https://hub.docker.com/v2
 IMAGE_NAME              ?= essex-basic
 BASE_IMAGE              ?= alpine:3.10
 VERSION                 := $(shell git describe --tags --abbrev=0 2>/dev/null || git rev-parse --abbrev-ref HEAD 2>/dev/null)
@@ -20,29 +22,44 @@ build: list
 		--build-arg BUILD_DATE=$(BUILD_DATE) \
 		--build-arg VCS_REF=$(VCS_REF) \
 		--build-arg VERSION=$(VERSION) \
-		--tag $(DOCKER_NAMESPACE)/$(IMAGE_NAME):latest \
-		--tag $(DOCKER_NAMESPACE)/$(IMAGE_NAME):$(VCS_REF) \
-		--tag $(DOCKER_NAMESPACE)/$(IMAGE_NAME):$(VERSION) \
+		--tag $(REPO_NAMESPACE)/$(IMAGE_NAME):latest \
+		--tag $(REPO_NAMESPACE)/$(IMAGE_NAME):$(VCS_REF) \
+		--tag $(REPO_NAMESPACE)/$(IMAGE_NAME):$(VERSION) \
 		--file Dockerfile .
 
 # List built images
 .PHONY: list
 list:
-	docker images $(DOCKER_NAMESPACE)/$(IMAGE_NAME) --filter "dangling=false"
+	docker images $(REPO_NAMESPACE)/$(IMAGE_NAME) --filter "dangling=false"
 
 # Run any tests
 .PHONY: test
 test:
-	docker run -t $(DOCKER_NAMESPACE)/$(IMAGE_NAME) env | grep VERSION | grep $(VERSION)
+	docker run -t $(REPO_NAMESPACE)/$(IMAGE_NAME) env | grep VERSION | grep $(VERSION)
 
 # Push images to repo
 .PHONY: push
 push:
-	docker push  $(DOCKER_NAMESPACE)/$(IMAGE_NAME):latest
-	docker push  $(DOCKER_NAMESPACE)/$(IMAGE_NAME):$(VCS_REF)
-	docker push  $(DOCKER_NAMESPACE)/$(IMAGE_NAME):$(VERSION)
+	echo "$$REPO_PASSWORD" | docker login -u "$(REPO_USERNAME)" --password-stdin; \
+		docker push  $(REPO_NAMESPACE)/$(IMAGE_NAME):latest; \
+		docker push  $(REPO_NAMESPACE)/$(IMAGE_NAME):$(VCS_REF); \
+		docker push  $(REPO_NAMESPACE)/$(IMAGE_NAME):$(VERSION);
+
+# Update README on registry
+.PHONY: push-readme
+push-readme:
+	echo "Authenticating to $(REPO_API_URL)"; \
+		token=$$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "$(REPO_USERNAME)", "password": "'"$$REPO_PASSWORD"'"}' $(REPO_API_URL)/users/login/ | jq -r .token); \
+		code=$$(jq -n --arg description "$$(<README.md)" '{"registry":"registry-1.docker.io","full_description": $$description }' | curl -s -o /dev/null  -L -w "%{http_code}" $(REPO_API_URL)/repositories/$(REPO_NAMESPACE)/$(IMAGE_NAME)/ -d @- -X PATCH -H "Content-Type: application/json" -H "Authorization: JWT $$token"); \
+		if [ "$$code" != "200" ]; \
+		then \
+			echo "Failed to update README.md"; \
+			exit 1; \
+		else \
+			echo "Success"; \
+		fi;
 
 # Remove existing images
 .PHONY: clean
 clean:
-	docker rmi $$(docker images $(DOCKER_NAMESPACE)/$(IMAGE_NAME) --format="{{.Repository}}:{{.Tag}}") --force
+	docker rmi $$(docker images $(REPO_NAMESPACE)/$(IMAGE_NAME) --format="{{.Repository}}:{{.Tag}}") --force
